import random
from tkinter import*
win = Tk()
ann=['Password Generator ', 'Version 3.0_2022.06.20', 'Enter the length:', 'Enter several sets:', 'Use the following characters','Enter the outer:', 'Generated', 'Clear']
win.title(ann[0]+ann[1])
win.geometry('614x253+400+300')
win.resizable(False,False)
win.config(bg='#333333')

def click():
    long = int(long_entry.get())
    groups =  int(group_entry.get())
    data = '' + add_entry.get() + data19.get() + dataaz.get() + dataAZ.get() + datachk.get()
    show = '\n'
    box.insert(1.0,show)
    for groups in range(int(groups)):
        password = ''.join(random.choices(data, k = int(long)))
        show = password + '\n'
        box.insert(1.0,show)
def delete():
    box.delete('1.0','end')

lab = Label(text=ann[1] + '    Made by YU KAI', bg='#333333', fg='#CCFFF7', font=15)
lab.grid(row=0, column=0, columnspan=2)
lab = Label(text=ann[2], bg='#262626', fg='#ffffff', font=15, width=15, anchor=W)
lab.grid(row=1, column=0)
lab = Label(text=ann[3], bg='#262626', fg='#ffffff', font=15, width=15, anchor=W)
lab.grid(row=2, column=0)
long_entry = Entry(bg='#ffffff', fg='#000000', font=15, width=20, justify=RIGHT)
long_entry.grid(row=1, column=1)
group_entry = Entry(bg='#ffffff', fg='#000000', font=15, width=20, justify=RIGHT)
group_entry.grid(row=2, column=1)
lab = Label(text=ann[4], bg='#262626', fg='#ffffff', font=15, width=35)
lab.grid(row=3, column=0, columnspan=2)
data19 = StringVar()
chk19 = Checkbutton(text='1-9', bg='#262626', fg='#ffffff', font=15, selectcolor='#000000', width=10, anchor=W, variable=data19, onvalue='123456789', offvalue='') 
chk19.grid(row=4, column=0)
dataaz = StringVar()
chkaz = Checkbutton(text='a-z', bg='#262626', fg='#ffffff', font=15, selectcolor='#000000', width=10, anchor=W, variable=dataaz, onvalue='abcdefghijklmnopqrstuvwxyz', offvalue='') 
chkaz.grid(row=4, column=1)
dataAZ = StringVar()
chkAZ = Checkbutton(text='A-Z', bg='#262626', fg='#ffffff', font=15, selectcolor='#000000', width=10, anchor=W, variable=dataAZ, onvalue='ABCDEFGHIJKLMNOPQRSTUVWXYZ', offvalue='') 
chkAZ.grid(row=5, column=0)
datachk = StringVar()
chk = Checkbutton(text='!@#$%^&*', bg='#262626', fg='#ffffff', font=15, selectcolor='#000000', width=10, anchor=W, variable=datachk, onvalue='!@#$%^&*', offvalue='') 
chk.grid(row=5, column=1)
lab = Label(text=ann[5], bg='#262626', fg='#ffffff', font=15, width=15, anchor=W)
lab.grid(row=6, column=0)
add_entry = Entry(bg='#ffffff', fg='#000000', font=15, width=20)
add_entry.grid(row=6, column=1)
btn = Button(text=ann[6], bg='#666666', fg='#ffffff',width=10, font=10, command=click)
btn.grid(row=7, column=0)
btn = Button(text=ann[7], bg='#666666', fg='#ffffff',width=10, font=10, command=delete)
btn.grid(row=7, column=1)
box=Text(bg='#000000', fg='#ffffff', width=35, height=15, font=10, bd=5)
box.grid(row=0, column=2, rowspan=8, columnspan=2)
win.mainloop()